### ISSUE TITLE
Following scripts are breaking with this release

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-examples#10]
Many of them due to moogli which is now built with openscene-3.2.1 . The problem should be due to new version of openscene library. 

- [x] paper-2015/Fig2C.py 

```
File "Fig2C.py", line 356, in <module>
    main()
  File "Fig2C.py", line 337, in main
    rdes = buildRdesigneur()
  File "Fig2C.py", line 148, in buildRdesigneur
    rd.addSpineProto() # This adds a version with an LCa channel by default.
  File "/usr/lib/python2.7/dist-packages/rdesigneur/rdesigneurProtos.py", line 348, in addSpineProto
    assert( moose.exists( parent ) ), "%s must exist" % parent
AssertionError: /library must exist
```
- [x] paper-2015/Fig2D.py 

```
ReadSwc: cells/ko20x-07.CNG.swc : NumSegs = 152, bad = 0, Validated = 1, numBranches = 40
ReadSwc::diagnostics: undef :   0
ReadSwc::diagnostics: soma :    3
ReadSwc::diagnostics: axon :    0
ReadSwc::diagnostics: dend :    59
ReadSwc::diagnostics: apical :  53
ReadSwc::diagnostics: dend_f :  7
ReadSwc::diagnostics: dend_e :  11
ReadSwc::diagnostics: custom :  0
ReadSwc::diagnostics: bad :     0
ReadSwc::diagnostics: undef :   0
ReadSwc::diagnostics: axon_f :  0
ReadSwc::diagnostics: axon_e :  0
ReadSwc::diagnostics: apical_f :        9
ReadSwc::diagnostics: apical_e :        10
Rdesigneur: Elec model has 152 compartments and 0 spines on 0 compartments.
Setting Up 3D Display
QGLTempContext: No GL capable X visuals available.
QGLTempContext: No GL capable X visuals available.
QGLContext::makeCurrent(): Cannot make invalid context current.
Error: OpenGL version test failed, requires valid graphics context.
Segmentation fault
````
- [x] paper-2015/Fig2E.py 

```
Rdesigneur: Elec model has 152 compartments and 0 spines on 0 compartments.
Setting Up 3D Display
QGLTempContext: No GL capable X visuals available.
QGLTempContext: No GL capable X visuals available.
QGLContext::makeCurrent(): Cannot make invalid context current.
Error: OpenGL version test failed, requires valid graphics context.
Segmentation fault
```

- [ ] paper-2015/Fig4_ReacDiff/rxdSpineSize.py 

```
Traceback (most recent call last):
  File "rxdSpineSize.py", line 293, in <module>
    showVisualization()
  File "rxdSpineSize.py", line 191, in showVisualization
    makeModel()
  File "rxdSpineSize.py", line 120, in makeModel
    rdes.buildModel( '/model' )
  File "/usr/lib/python2.7/dist-packages/rdesigneur/rdesigneur.py", line 199, in buildModel
    self.buildAdaptors()
  File "/usr/lib/python2.7/dist-packages/rdesigneur/rdesigneur.py", line 489, in buildAdaptors
    self._buildAdaptor( mesh, i[2], i[3], name, i[1], False, i[4], i[5] )
  File "/usr/lib/python2.7/dist-packages/rdesigneur/rdesigneur.py", line 1230, in _buildAdaptor
    elecComptList = moose.vec( mesh.elecComptList[0].path + '/../spine' )
IndexError: tuple index out of range

```

**Comment by hrani** [comment]
Fig2C.py This is moose problem and fixed by Upi which is also commited and working

**Comment by hrani** [comment]
**paper-2015/Fig5_CellMultiscale/Fig5BCD.py**  not working. (This is nothing to do with moogli or openscene-3.2.1)
This rdesigneur problem.

Usage: name, path, [spacing, spacingDistrib, size, sizeDistrib, angle, angleDistrib]
Warning: Dsolve::setNinit: Eref z out of range 1, 0
File "moose-core/python/rdesigneur/rdesigneur.py", line 1231, in _buildAdaptor
    elecComptList = moose.vec( mesh.elecComptList[0].path + '/../spine' )
IndexError: tuple index out of range

**Comment by dilawar** [comment]
Above scripts worked with latest release on OpenSUSE-42.2. There is some trouble with OpenScene graph. 

File `Fig4_ReacDiff/rxdSpineSize.py` still failing with the same error message.

**Comment by dilawar** [comment]
They have me marked BROEN #30
